=== nicbraden/XML-Airport/XML-Airport/flightSchema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--
    File:           flightSchema.xsd
    Author:         Nicole Braden
    Date:           Feb 7, 2020
    Description:    Project 1 - Airport
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="flights">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="airport">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Flights at London International Airport" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="date" type="xs:date" />
                <xs:element name="time" type="xs:time" />
                <xs:element name="arrivals" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="arrival" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="airline-a" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="flight" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="1" />
                                                                <xs:maxInclusive value="9999" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="arriving-from" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Abbotsford" />
                                                                <xs:enumeration value="Calgary" />
                                                                <xs:enumeration value="Cancun" />
                                                                <xs:enumeration value="Cayo Santa Maria" />
                                                                <xs:enumeration value="Edmonton" />
                                                                <xs:enumeration value="Hamilton" />
                                                                <xs:enumeration value="Las Vegas" />
                                                                <xs:enumeration value="Montego Bay" />
                                                                <xs:enumeration value="Montreal" />
                                                                <xs:enumeration value="Orlando" />
                                                                <xs:enumeration value="Ottawa" />
                                                                <xs:enumeration value="Puerto Plata" />
                                                                <xs:enumeration value="Punta Cana" />
                                                                <xs:enumeration value="Sault Ste Marie" />
                                                                <xs:enumeration value="Toronto" />
                                                                <xs:enumeration value="Varadaro" />
                                                                <xs:enumeration value="Winnipeg" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="scheduled-time" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:time">
                                                                <xs:pattern value="[0-2][0-9]:[0-5][0-9]:00" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="actual-time" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:time">
                                                                <xs:pattern value="[0-2][0-9]:[0-5][0-9]:00" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="status" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Arrived" />
                                                                <xs:enumeration value="Cancelled" />
                                                                <xs:enumeration value="Diverted" />
                                                                <xs:enumeration value="Early" />
                                                                <xs:enumeration value="Late" />
                                                                <xs:enumeration value="On Time" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="company">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="Air Canada" />
                                                            <xs:enumeration value="Sunwing" />
                                                            <xs:enumeration value="Air Transat" />
                                                            <xs:enumeration value="Swoop" />
                                                            <xs:enumeration value="WestJet" />
                                                            <xs:enumeration value="WestJet Encore" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="departures" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="depature" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="departure-airline" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="departure-flight" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="1" />
                                                                <xs:maxInclusive value="9999" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="leaving-from" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Abbotsford" />
                                                                <xs:enumeration value="Calgary" />
                                                                <xs:enumeration value="Cancun" />
                                                                <xs:enumeration value="Cayo Santa Maria" />
                                                                <xs:enumeration value="Edmonton" />
                                                                <xs:enumeration value="Hamilton" />
                                                                <xs:enumeration value="Las Vegas" />
                                                                <xs:enumeration value="Montego Bay" />
                                                                <xs:enumeration value="Montreal" />
                                                                <xs:enumeration value="Orlando" />
                                                                <xs:enumeration value="Ottawa" />
                                                                <xs:enumeration value="Puerto Plata" />
                                                                <xs:enumeration value="Punta Cana" />
                                                                <xs:enumeration value="Sault Ste Marie" />
                                                                <xs:enumeration value="Toronto" />
                                                                <xs:enumeration value="Varadaro" />
                                                                <xs:enumeration value="Winnipeg" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="scheduled-departure-time" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:time">
                                                                <xs:pattern value="[0-2][0-9]:[0-5][0-9]:00" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="actual-depature-time" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:time">
                                                                <xs:pattern value="[0-2][0-9]:[0-5][0-9]:00" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="departure-status" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Cancelled" />
                                                                <xs:enumeration value="Departed" />
                                                                <xs:enumeration value="Delayed" />
                                                                <xs:enumeration value="On Time" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="name">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="Air Canada" />
                                                            <xs:enumeration value="Sunwing" />
                                                            <xs:enumeration value="Air Transat" />
                                                            <xs:enumeration value="Swoop" />
                                                            <xs:enumeration value="WestJet" />
                                                            <xs:enumeration value="WestJet Encore" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nicbraden/XML-Airport/XML-Airport/flights.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
    File:           flights.xml
    Author:         Nicole Braden
    Date:           Feb 7, 2020
    Description:    Project 1 - Airport
-->
<flights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flightSchema.xsd">
  <airport>Flights at London International Airport</airport>
  <date>2020-02-07</date>
  <time>11:19:00</time>
  <arrivals>
    <arrival>
      <airline-a company="Swoop">
        <flight>8649</flight>
        <arriving-from>Toronto</arriving-from>
        <scheduled-time>14:31:00</scheduled-time>
        <actual-time>12:43:00</actual-time>
        <status>Arrived</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="WestJet">
        <flight>3511</flight>
        <arriving-from>Toronto</arriving-from>
        <scheduled-time>17:58:00</scheduled-time>
        <actual-time>17:40:00</actual-time>
        <status>Early</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Swoop">
        <flight>833</flight>
        <arriving-from>Las Vegas</arriving-from>
        <scheduled-time>19:37:00</scheduled-time>
        <actual-time>19:43:00</actual-time>
        <status>Late</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Sunwing">
        <flight>740</flight>
        <arriving-from>Ottawa</arriving-from>
        <scheduled-time>09:25:00</scheduled-time>
        <actual-time>09:25:00</actual-time>
        <status>On Time</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Swoop">
        <flight>342</flight>
        <arriving-from>Abbotsford</arriving-from>
        <scheduled-time>21:52:00</scheduled-time>
        <actual-time>22:27:00</actual-time>
        <status>Late</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="WestJet">
        <flight>736</flight>
        <arriving-from>Calgary</arriving-from>
        <scheduled-time>00:19:00</scheduled-time>
        <actual-time>00:19:00</actual-time>
        <status>On Time</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Swoop">
        <flight>208</flight>
        <arriving-from>Edmonton</arriving-from>
        <scheduled-time>11:38:00</scheduled-time>
        <actual-time>11:38:00</actual-time>
        <status>On Time</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Air Canada">
        <flight>8665</flight>
        <arriving-from>Montreal</arriving-from>
        <scheduled-time>15:08:00</scheduled-time>
        <actual-time>15:08:00</actual-time>
        <status>Arrived</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Air Canada">
        <flight>8643</flight>
        <arriving-from>Toronto</arriving-from>
        <scheduled-time>08:46:00</scheduled-time>
        <actual-time>08:46:00</actual-time>
        <status>On Time</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="WestJet">
        <flight>3511</flight>
        <arriving-from>Toronto</arriving-from>
        <scheduled-time>17:58:00</scheduled-time>
        <actual-time>17:58:00</actual-time>
        <status>On Time</status>
      </airline-a>
    </arrival>
  </arrivals>
  <departures>
    <depature>
      <departure-airline name="WestJet">
        <departure-flight>3508</departure-flight>
        <leaving-from>Toronto</leaving-from>
        <scheduled-departure-time>18:30:00</scheduled-departure-time>
        <actual-depature-time>18:30:00</actual-depature-time>
        <departure-status>On Time</departure-status>
      </departure-airline>
    </depature>
    <depature>
      <departure-airline name="Air Canada">
        <departure-flight>8646</departure-flight>
        <leaving-from>Toronto</leaving-from>
        <scheduled-departure-time>12:05:00</scheduled-departure-time>
        <actual-depature-time>12:59:00</actual-depature-time>
        <departure-status>Cancelled</departure-status>
      </departure-airline>
    </depature>
    <depature>
      <departure-airline name="Swoop">
        <departure-flight>539</departure-flight>
        <leaving-from>Edmonton</leaving-from>
        <scheduled-departure-time>22:40:00</scheduled-departure-time>
        <actual-depature-time>23:20:00</actual-depature-time>
        <departure-status>Delayed</departure-status>
      </departure-airline>
    </depature>
    <depature>
      <departure-airline name="Sunwing">
        <departure-flight>740</departure-flight>
        <leaving-from>Montego Bay</leaving-from>
        <scheduled-departure-time>10:15:00</scheduled-departure-time>
        <actual-depature-time>10:15:00</actual-depature-time>
        <departure-status>On Time</departure-status>
      </departure-airline>
    </depature>
    <depature>
      <departure-airline name="Swoop">
        <departure-flight>221</departure-flight>
        <leaving-from>Abbotsford</leaving-from>
        <scheduled-departure-time>12:25:00</scheduled-departure-time>
        <actual-depature-time>12:25:00</actual-depature-time>
        <departure-status>On Time</departure-status>
      </departure-airline>
    </depature>
  </departures>
</flights>

=== nicbraden/XML-Airport/XML-Airport/secondxml.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
    File:           second.xml
    Author:         Nicole Braden
    Date:           Feb 7, 2020
    Description:    Project 1 - Airport
-->
<flights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flightSchema.xsd">
  <airport>Flights at London International Airport</airport>
  <date>2020-02-07</date>
  <time>11:19:00</time>
  <arrivals>
    <arrival>
      <airline-a company="Air Canada">
        <flight>8645</flight>
        <arriving-from>Toronto</arriving-from>
        <scheduled-time>11:41:00</scheduled-time>
        <actual-time>11:52:00</actual-time>
        <status>Arrived</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Swoop">
        <flight>208</flight>
        <arriving-from>Edmonton</arriving-from>
        <scheduled-time>12:38:00</scheduled-time>
        <actual-time>12:22:00</actual-time>
        <status>Arrived</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Air Canada">
        <flight>8659</flight>
        <arriving-from>Ottawa</arriving-from>
        <scheduled-time>13:50:00</scheduled-time>
        <actual-time>14:45:00</actual-time>
        <status>Diverted</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Swoop">
        <flight>350</flight>
        <arriving-from>Abbotsford</arriving-from>
        <scheduled-time>15:12:00</scheduled-time>
        <actual-time>15:49:00</actual-time>
        <status>Late</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Air Transat">
        <flight>023</flight>
        <arriving-from>Hamilton</arriving-from>
        <scheduled-time>17:10:00</scheduled-time>
        <actual-time>17:10:00</actual-time>
        <status>On Time</status>
      </airline-a>
    </arrival>
    <arrival>
      <airline-a company="Sunwing">
        <flight>107</flight>
        <arriving-from>Varadaro</arriving-from>
        <scheduled-time>18:30:00</scheduled-time>
        <actual-time>18:30:00</actual-time>
        <status>On Time</status>
      </airline-a>
    </arrival>
  </arrivals>
  <departures>
    <depature>
      <departure-airline name="Air Canada">
        <departure-flight>8646</departure-flight>
        <leaving-from>Toronto</leaving-from>
        <scheduled-departure-time>12:05:00</scheduled-departure-time>
        <actual-depature-time>12:27:00</actual-depature-time>
        <departure-status>Departed</departure-status>
      </departure-airline>
    </depature>
    <depature>
      <departure-airline name="Swoop">
        <departure-flight>239</departure-flight>
        <leaving-from>Edmonton</leaving-from>
        <scheduled-departure-time>13:25:00</scheduled-departure-time>
        <actual-depature-time>13:22:00</actual-depature-time>
        <departure-status>Departed</departure-status>
      </departure-airline>
    </depature>
    <depature>
      <departure-airline name="Air Canada">
        <departure-flight>8660</departure-flight>
        <leaving-from>Ottawa</leaving-from>
        <scheduled-departure-time>14:15:00</scheduled-departure-time>
        <actual-depature-time>15:05:00</actual-depature-time>
        <departure-status>Delayed</departure-status>
      </departure-airline>
    </depature>
    <depature>
      <departure-airline name="Sunwing">
        <departure-flight>462</departure-flight>
        <leaving-from>Punta Cana</leaving-from>
        <scheduled-departure-time>09:30:00</scheduled-departure-time>
        <actual-depature-time>09:30:00</actual-depature-time>
        <departure-status>On Time</departure-status>
      </departure-airline>
    </depature>
    <depature>
      <departure-airline name="Swoop">
        <departure-flight>836</departure-flight>
        <leaving-from>Orlando</leaving-from>
        <scheduled-departure-time>16:00:00</scheduled-departure-time>
        <actual-depature-time>16:00:00</actual-depature-time>
        <departure-status>On Time</departure-status>
      </departure-airline>
    </depature>
    <depature>
      <departure-airline name="WestJet">
        <departure-flight>3508</departure-flight>
        <leaving-from>Calgary</leaving-from>
        <scheduled-departure-time>06:00:00</scheduled-departure-time>
        <actual-depature-time>06:00:00</actual-depature-time>
        <departure-status>On Time</departure-status>
      </departure-airline>
    </depature>
  </departures>
</flights>
